var settings = {
	data:{},
	container:'container', 
	id:'map',
	accessToken:'pk.eyJ1IjoibWljaGFlbGZyZWVtYW4iLCJhIjoibE5leG9MRSJ9.YHTl3OfWurGattFSUzwhag',
	date:'2014-4-22',
	dateNumber:112,
	encodeOpacity:false, 
	encodeWidth:false, 
	defaultOpacity:.3,
	defaultRadius:50,
	finalOpacity:.2,
	defaultWidth:2,
	opacityRange:[.01, .1], 
	widthRange:[1,20],
	showMap:false, 
	dataFile:'data/data_start_stop.csv',
	stationFile:'data/new_stations.csv',
	color:'#2FCAFC', 
	backgroundColor:'black', 
	dataSource:'database',
	timeFactor:250,
	maxSpeed:10,
	speedChange: -1,
	interval:10000, 
	disappear:true,
	disappearTime:0,
	center:[41.8944829010142, -87.6595687866211],
	zoom:12, 
	speedUp:true,
	startMinute:0, 
	totalMinutes:24*60,
	drawStations:true,
	sizeStations:true, 
	minRadius:10, 
	maxRadius:500, 
	growCircles: true,
	circleIncrement:1,
	startRadius:50

}